### ISSUE TITLE
关于cmake问题

### ISSUE THREAD

**Issue by Joll123** [ctwgL/webrtc_agc2#1]
你好，最近在学习下agc2，当我在根目录下cmake . 时出现一下错误，应该怎么处理。
  add_subdirectory given source
  "/Users/jinhonglong/Desktop/chromium/webrtc_agc2/webrtc/third_party/jsoncpp/source"
  which is not an existing directory.
不存在source。

**Comment by ctwgL** [comment]
已经上传了缺少的文件
